name: Build workflow
on: push

jobs:
  build:
    name: Build job
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # .NET core and node.js are installed on ubuntu-18.04 by default

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run build
